import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'app_title': 'أَذْكَارِي',
      'morning_azkar': 'أذكار الصباح',
      'evening_azkar': 'أذكار المساء',
      'after_pray_azkar': 'أذكار بعد الصلاة',
      'sleep_azkar': 'أذكار النوم',
      'friday_sunan': 'سنن الجمعة',
      'allah_names': 'أسماء الله الحسنى',
      'daily_werd': 'وردك اليومي',
      'various_azkar': 'أذكار متفرقة',
      'roqiah': 'الرقية الشرعية',
      'dhikr_virtue': 'فضل الذكر',
      'dua_virtue': 'فضل الدعاء',
      'allah_verse':
          'هُوَ اللَّهُ الَّذِي لَا إِلَهَ إِلَّا هُوَ الرَّحْمَنُ الرَّحِيمُ المَلِكُ القُدُّوسُ السَّلَامُ المُؤْمِنُ المُهَيْمِنُ العَزِيزُ الجَبَّارُ المُتَكَبِّرُ',
      'subhan_allah': 'سُبْحَانَ اللَّهِ عَمَّا يُشْرِكُونَ',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'choose_language': 'اختر اللغة',
      'themes': 'الألوان والسمات',
      'choose_theme': 'اختر اللون',
      'theme_emerald': 'الزمردي (الأصلي)',
      'theme_midnight': 'الأزرق الملكي',
      'theme_rose': 'الوردي الدافئ',
      'theme_forest': 'الغابة الهادئة',
      'theme_sunset': 'الغروب الذهبي',
      'theme_sepia': 'السيبيا الكلاسيكي',
      'comprehensive_dua': 'جوامع الدعاء',
      'contact_developer': 'تواصل مع المُطَوِّر',
      'meet_developer': 'Meet the Developer',
      'developer_name': 'Abdelmoneim Adel',
      'developer_title': 'Software Mobile Application Engineer',
      'electronic_rosary': 'السبحة الإلكترونية',
      'total_count': 'العدد الكلي',
      'reset': 'إعادة ضبط',
      'tap_to_open_rosary': 'اضغط هنا لفتح السبحة الإلكترونية',
      'add_zekr': 'إضافة ذكر جديد',
      'cancel': 'إلغاء',
      'add': 'إضافة',
      'total_today': 'مجموع اليوم',
      'view_history': 'عرض السجل',
      'history': 'سجل الأذكار',
      'monthly_report': 'التقرير الشهري',
      'count_suffix': 'عدة',
      'daily_record': 'اليوم',
      'best': 'أفضل أداء للذكر',
      'overall_best': 'أفضل مجموع يومي',
      'insights': 'إحصائيات الذكر',
      'insights_for': 'إحصائيات لـ',
      'today': 'اليوم',
      'no_history_yet': 'لا يوجد سجل بعد',
      'delete_zekr': 'حذف الذكر',
      'confirm_delete': 'هل أنت متأكد من حذف',
      'delete': 'حذف',
      'permissions': 'الأذونات',
      'permissions_subtitle': 'تحكم في أذونات التطبيق',
      'perm_notifications': 'الإشعارات',
      'perm_notifications_sub': 'إرسال أذكار ومواقيت الصلاة',
      'perm_location': 'الموقع الجغرافي',
      'perm_location_sub': 'حساب مواقيت الصلاة بدقة',
      'perm_exact_alarm': 'التنبيهات الدقيقة',
      'perm_exact_alarm_sub': 'جدولة الإشعارات في الوقت المحدد',
      'perm_enabled': 'مفعّل',
      'perm_disabled': 'معطّل',
      'perm_all_granted': 'مكتمل ✓',
      'perm_incomplete': 'ناقص',
      'perm_loading': 'جاري التحقق من الأذونات...',
      'perm_refresh': 'تحديث',
      'perm_open_settings': 'إعدادات التطبيق',
      'next_prayer': 'الصلاة القادمة',
      'time_remaining': 'متبقي',
      'prayer_times_loading': 'جاري تحميل المواقيت...',
      'prayer_fajr': 'الفجر',
      'prayer_sunrise': 'الشروق',
      'prayer_dhuhr': 'الظهر',
      'prayer_asr': 'العصر',
      'prayer_maghrib': 'المغرب',
      'prayer_isha': 'العشاء',
    },
    'en': {
      'app_title': 'Athkary',
      'morning_azkar': 'Morning Azkar',
      'evening_azkar': 'Evening Azkar',
      'after_pray_azkar': 'After Prayer Azkar',
      'sleep_azkar': 'Sleep Azkar',
      'friday_sunan': 'Friday Sunan',
      'allah_names': 'Names of Allah',
      'daily_werd': 'Daily Werd',
      'various_azkar': 'Various Azkar',
      'roqiah': 'Ruqyah',
      'dhikr_virtue': 'Virtue of Dhikr',
      'dua_virtue': 'Virtue of Dua',
      'allah_verse':
          'He is Allah, other than whom there is no deity, the Beneficent, the Merciful, the King, the Holy, the Peace, the Giver of Security, the Guardian...',
      'subhan_allah':
          'Exalted is Allah above whatever they associate with Him.',
      'settings': 'Settings',
      'language': 'Language',
      'choose_language': 'Choose Language',
      'themes': 'Themes',
      'choose_theme': 'Choose Theme',
      'theme_emerald': 'Emerald (Default)',
      'theme_midnight': 'Midnight Royal',
      'theme_rose': 'Desert Rose',
      'theme_forest': 'Forest Serenity',
      'theme_sunset': 'Sunset Harmony',
      'theme_sepia': 'Classic Sepia',
      'comprehensive_dua': 'Comprehensive Supplications',
      'contact_developer': 'Contact Developer',
      'meet_developer': 'Meet the Developer',
      'developer_name': 'Abdelmoneim Adel',
      'developer_title': 'Software Mobile Application Engineer',
      'electronic_rosary': 'Electronic Rosary',
      'total_count': 'Total Count',
      'reset': 'Reset',
      'tap_to_open_rosary': 'Tap here to open the electronic rosary',
      'add_zekr': 'Add New Zekr',
      'cancel': 'Cancel',
      'add': 'Add',
      'total_today': 'Total Today',
      'view_history': 'View History',
      'history': 'Zikr History',
      'monthly_report': 'Monthly Report',
      'count_suffix': 'counts',
      'daily_record': 'Today',
      'best': 'Zekr Best',
      'overall_best': 'Overall Daily Best',
      'insights': 'Rosary Insights',
      'insights_for': 'Insights for',
      'today': 'Today',
      'no_history_yet': 'No history yet',
      'delete_zekr': 'Delete Dhikr',
      'confirm_delete': 'Are you sure you want to delete',
      'delete': 'Delete',
      'permissions': 'Permissions',
      'permissions_subtitle': 'Manage app permissions',
      'perm_notifications': 'Notifications',
      'perm_notifications_sub': 'Send azkar and prayer time alerts',
      'perm_location': 'Location',
      'perm_location_sub': 'Calculate accurate prayer times',
      'perm_exact_alarm': 'Exact Alarms',
      'perm_exact_alarm_sub': 'Schedule notifications at precise times',
      'perm_enabled': 'Enabled',
      'perm_disabled': 'Disabled',
      'perm_all_granted': 'Complete ✓',
      'perm_incomplete': 'Incomplete',
      'perm_loading': 'Checking permissions...',
      'perm_refresh': 'Refresh',
      'perm_open_settings': 'App Settings',
      'next_prayer': 'Next Prayer',
      'time_remaining': 'Remaining',
      'prayer_times_loading': 'Loading prayer times...',
      'prayer_fajr': 'Fajr',
      'prayer_sunrise': 'Sunrise',
      'prayer_dhuhr': 'Dhuhr',
      'prayer_asr': 'Asr',
      'prayer_maghrib': 'Maghrib',
      'prayer_isha': 'Isha',
    },
    'fr': {
      'app_title': 'Athkary',
      'morning_azkar': 'Azkar du Matin',
      'evening_azkar': 'Azkar du Soir',
      'after_pray_azkar': 'Azkar après la Prière',
      'sleep_azkar': 'Azkar du Sommeil',
      'friday_sunan': 'Sunan du Vendredi',
      'allah_names': 'Noms d\'Allah',
      'daily_werd': 'Werd Quotidien',
      'various_azkar': 'Azkar Divers',
      'roqiah': 'Roqya',
      'dhikr_virtue': 'Vertu du Dhikr',
      'dua_virtue': 'Vertu de l\'Invocation',
      'allah_verse':
          'C\'est Lui Allah. Nulle divinité sauf Lui; Le Souverain, Le Pur, L\'Apaisant, Le Rassurant, Le Prédominant, Le Puissant, Le Contraignant, Le Superbe.',
      'subhan_allah':
          'Gloire à Allah! Il est bien au-dessus de ce qu\'ils Lui associent.',
      'settings': 'Paramètres',
      'language': 'Langue',
      'choose_language': 'Choisir la langue',
      'themes': 'Thèmes',
      'choose_theme': 'Choisir le thème',
      'theme_emerald': 'Émeraude (Par défaut)',
      'theme_midnight': 'Bleu Royal',
      'theme_rose': 'Rose du Désert',
      'theme_forest': 'Forêt Sérénité',
      'theme_sunset': 'Harmonie du Coucher de Soleil',
      'theme_sepia': 'Sépia Classique',
      'comprehensive_dua': 'Invocations Complètes',
      'contact_developer': 'Contacter le Développeur',
      'meet_developer': 'Rencontrer le Développeur',
      'developer_name': 'Abdelmoneim Adel',
      'developer_title': 'Ingénieur Logiciel d\'Applications Mobiles',
      'electronic_rosary': 'Chapelet Électronique',
      'total_count': 'Compte Total',
      'reset': 'Réinitialiser',
      'tap_to_open_rosary': 'Appuyez ici pour ouvrir le chapelet électronique',
      'add_zekr': 'Ajouter un nouveau Zekr',
      'cancel': 'Annuler',
      'add': 'Ajouter',
      'total_today': 'Total Aujourd\'hui',
      'view_history': 'Voir l\'historique',
      'history': 'Historique du Zikr',
      'today': 'Aujourd\'hui',
      'no_history_yet': 'Pas encore d\'historique',
      'delete_zekr': 'Supprimer le Dhikr',
      'confirm_delete': 'Voulez-vous vraiment supprimer',
      'delete': 'Supprimer',
      'permissions': 'Autorisations',
      'permissions_subtitle': 'Gérer les autorisations',
      'perm_notifications': 'Notifications',
      'perm_notifications_sub': 'Envoyer des rappels et horaires de prière',
      'perm_location': 'Localisation',
      'perm_location_sub': 'Calculer les horaires de prière avec précision',
      'perm_exact_alarm': 'Alarmes Précises',
      'perm_exact_alarm_sub': 'Planifier les notifications à l\'heure exacte',
      'perm_enabled': 'Activé',
      'perm_disabled': 'Désactivé',
      'perm_all_granted': 'Complet ✓',
      'perm_incomplete': 'Incomplet',
      'perm_loading': 'Vérification des autorisations...',
      'perm_refresh': 'Actualiser',
      'perm_open_settings': 'Paramètres',
      'next_prayer': 'Prochaine prière',
      'time_remaining': 'Restant',
      'prayer_times_loading': 'Chargement des horaires...',
      'prayer_fajr': 'Fajr',
      'prayer_sunrise': 'Lever du soleil',
      'prayer_dhuhr': 'Dhuhr',
      'prayer_asr': 'Asr',
      'prayer_maghrib': 'Maghrib',
      'prayer_isha': 'Icha',
    },
    'de': {
      'app_title': 'Athkary',
      'morning_azkar': 'Morgendliche Azkar',
      'evening_azkar': 'Abendliche Azkar',
      'after_pray_azkar': 'Azkar nach dem Gebet',
      'sleep_azkar': 'Schlaf-Azkar',
      'friday_sunan': 'Freitags-Sunan',
      'allah_names': 'Namen Allahs',
      'daily_werd': 'Tägliches Werd',
      'various_azkar': 'Verschiedene Azkar',
      'roqiah': 'Ruqyah',
      'dhikr_virtue': 'Tugend des Dhikr',
      'dua_virtue': 'Tugend des Dua',
      'allah_verse':
          'Er ist Allah, außer dem es keinen Gott gibt, der König, der Heilige, der Friede, der Gewährer der Sicherheit, der Wächter...',
      'subhan_allah': 'Gepriesen sei Allah über das, was sie Ihm beigesellen.',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'choose_language': 'Sprache wählen',
      'themes': 'Themes',
      'choose_theme': 'Thema wählen',
      'theme_emerald': 'Smaragd (Standard)',
      'theme_midnight': 'Königliches Blau',
      'theme_rose': 'Wüstenrose',
      'theme_forest': 'Waldstille',
      'theme_sunset': 'Sonnenuntergang Harmonie',
      'theme_sepia': 'Klassisches Sepia',
      'comprehensive_dua': 'Umfassende Bittgebete',
      'contact_developer': 'Entwickler Kontaktieren',
      'meet_developer': 'Den Entwickler Treffen',
      'developer_name': 'Abdelmoneim Adel',
      'developer_title': 'Software-Ingenieur für Mobile Anwendungen',
      'electronic_rosary': 'Elektronischer Rosenkranz',
      'total_count': 'Gesamtzählung',
      'reset': 'Zurücksetzen',
      'tap_to_open_rosary':
          'Tippen Sie hier, um den elektronischen Rosenkranz zu öffnen',
      'add_zekr': 'Neuen Zekr hinzufügen',
      'cancel': 'Abbrechen',
      'add': 'Hinzufügen',
      'total_today': 'Heute Insgesamt',
      'view_history': 'Verlauf anzeigen',
      'history': 'Zikr-Verlauf',
      'today': 'Heute',
      'no_history_yet': 'Noch kein Verlauf',
      'delete_zekr': 'Dhikr löschen',
      'confirm_delete': 'Sind Sie sicher, dass Sie löschen möchten',
      'delete': 'Löschen',
      'permissions': 'Berechtigungen',
      'permissions_subtitle': 'App-Berechtigungen verwalten',
      'perm_notifications': 'Benachrichtigungen',
      'perm_notifications_sub': 'Azkar und Gebetszeiten senden',
      'perm_location': 'Standort',
      'perm_location_sub': 'Genaue Gebetszeiten berechnen',
      'perm_exact_alarm': 'Genaue Alarme',
      'perm_exact_alarm_sub': 'Benachrichtigungen zur genauen Zeit planen',
      'perm_enabled': 'Aktiviert',
      'perm_disabled': 'Deaktiviert',
      'perm_all_granted': 'Vollständig ✓',
      'perm_incomplete': 'Unvollständig',
      'perm_loading': 'Berechtigungen werden geprüft...',
      'perm_refresh': 'Aktualisieren',
      'perm_open_settings': 'App-Einstellungen',
      'next_prayer': 'Nächstes Gebet',
      'time_remaining': 'Verbleibend',
      'prayer_times_loading': 'Gebetszeiten laden...',
      'prayer_fajr': 'Fadschr',
      'prayer_sunrise': 'Sonnenaufgang',
      'prayer_dhuhr': 'Dhuhr',
      'prayer_asr': 'Asr',
      'prayer_maghrib': 'Maghrib',
      'prayer_isha': 'Ischa',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ar', 'en', 'fr', 'de'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension LocalizationExtension on BuildContext {
  String translate(String key) {
    return AppLocalizations.of(this)?.translate(key) ?? key;
  }
}
